# Generated by Django 4.0.3 on 2022-03-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='data_de_publicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de publicação'),
        ),
        migrations.AddField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
    ]
